import React,{useEffect,useMemo,useState}from"react";
import{initializeApp}from"firebase/app";
import{getAuth,signInAnonymously,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,linkWithPopup}from"firebase/auth";
import{getFirestore,doc,setDoc,getDoc,updateDoc,onSnapshot,collection,query,orderBy,limit,getDocs,serverTimestamp}from"firebase/firestore";

const c={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
let auth=null,db=null;if(c.apiKey&&c.projectId){const a=initializeApp(c);auth=getAuth(a);db=getFirestore(a)}
const E=Array(9).fill(null),L=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function win(b){for(const[a,x,y]of L)if(b[a]&&b[a]===b[x]&&b[a]===b[y])return b[a];return b.every(Boolean)?"draw":null}
function ai(b,me="O"){const op=me==="X"?"O":"X";function mm(x,t){const w=win(x);if(w===me)return 10;if(w===op)return-10;if(w==="draw")return 0;let s=[];x.forEach((v,i)=>{if(!v){let y=[...x];y[i]=t;s.push(mm(y,t===me?op:me))}});return t===me?Math.max(...s):Math.min(...s)}let best=-Infinity,m=-1;b.forEach((v,i)=>{if(!v){let y=[...b];y[i]=me;let s=mm(y,op);if(s>best){best=s;m=i}}});return m}
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();

export default function App(){
const[user,setUser]=useState(null),[name,setName]=useState(""),[stats,setStats]=useState({wins:0,losses:0,draws:0}),[mode,setMode]=useState("home"),[b,setB]=useState(E),[turn,setTurn]=useState("X"),[room,setRoom]=useState(""),[mark,setMark]=useState("X"),[status,setStatus]=useState(""),[leaders,setLeaders]=useState([]),[copied,setCopied]=useState(false);
const result=useMemo(()=>win(b),[b]);
useEffect(()=>{if(auth){signInAnonymously(auth).catch(e=>setStatus(e.code));return onAuthStateChanged(auth,setUser)}},[]);
useEffect(()=>{if(!user||!db)return;getDoc(doc(db,"players",user.uid)).then(s=>{if(s.exists()){setName(s.data().name||"");setStats(s.data().stats||stats)}})},[user]);
useEffect(()=>{const r=new URLSearchParams(location.search).get("room");if(r){setRoom(r.toUpperCase());setMode("join")}},[]);
useEffect(()=>{if(!db||!room||mode!=="online")return onSnapshot(doc(db,"games",room),s=>{if(!s.exists()){setStatus("ROOM NOT FOUND");return}const g=s.data();setB(g.board||E);setTurn(g.turn||"X");setMark(g.host===user?.uid?"X":g.guest===user?.uid?"O":mark);setStatus(g.status==="waiting"?"WAITING FOR OPPONENT":g.status==="done"?(g.result||"GAME OVER"):"LIVE MATCH")})},[room,mode,user]);
async function save(r){if(!db||!user||!name.trim())return;let n={...stats};if(r==="win")n.wins++;if(r==="loss")n.losses++;if(r==="draw")n.draws++;setStats(n);await setDoc(doc(db,"players",user.uid),{name:name.trim(),stats:n,updatedAt:serverTimestamp()},{merge:true})}
function bot(i){if(result||b[i]||turn!=="X")return;let x=[...b];x[i]="X";let w=win(x);setB(x);if(w){setStatus(w==="draw"?"DRAW":"YOU WIN");save(w==="X"?"win":"draw");return}setTurn("O");setTimeout(()=>{let m=ai(x);if(m<0)return;let y=[...x];y[m]="O";let z=win(y);setB(y);if(z){setStatus(z==="draw"?"DRAW":"PRO BOT WINS");save(z==="O"?"loss":"draw")}else setTurn("X")},280)}
async function create(){if(!db||!user){setStatus("FIREBASE NOT READY");return}let id=code();setRoom(id);setMark("X");setMode("online");await setDoc(doc(db,"games",id),{board:E,turn:"X",status:"waiting",host:user.uid,guest:null,result:null,createdAt:serverTimestamp()})}
async function join(id=room){if(!db||!user)return;id=id.trim().toUpperCase();let r=doc(db,"games",id),s=await getDoc(r);if(!s.exists()){setStatus("ROOM NOT FOUND");return}let g=s.data();if(g.host===user.uid)setMark("X");else{if(g.guest&&g.guest!==user.uid){setStatus("ROOM FULL");return}setMark("O");await updateDoc(r,{guest:user.uid,status:"playing"})}setRoom(id);setMode("online")}
async function move(i){if(!db||!room||result||b[i]||turn!==mark)return;let x=[...b];x[i]=mark;let w=win(x);await updateDoc(doc(db,"games",room),{board:x,turn:mark==="X"?"O":"X",status:w?"done":"playing",result:w?(w==="draw"?"DRAW":w+" WINS"):null,lastMove:i,lastMoveAt:serverTimestamp()});if(w)save(w===mark?"win":w==="draw"?"draw":"loss")}
async function rematch(){if(mode==="online"&&db&&room)await updateDoc(doc(db,"games",room),{board:E,turn:"X",status:"playing",result:null,lastMove:null});else{setB(E);setTurn("X");setStatus("")}}
async function google(){if(!auth)return;try{if(user?.isAnonymous)await linkWithPopup(user,new GoogleAuthProvider());else await signInWithPopup(auth,new GoogleAuthProvider());setStatus("GOOGLE PROFILE LINKED")}catch(e){setStatus(e.code||e.message)}}
async function board(){if(!db)return;let q=query(collection(db,"players"),orderBy("stats.wins","desc"),limit(10)),s=await getDocs(q);setLeaders(s.docs.map(d=>d.data()));setMode("leaders")}
const link=room?`${location.origin}${location.pathname}?room=${room}`:"";
if(mode==="home")return <Home name={name} setName={setName} google={google} stats={stats} bot={()=>{setB(E);setTurn("X");setStatus("");setMode("bot")}} online={()=>setMode("join")} leaders={board} status={status}/>;
if(mode==="leaders")return <main><Top t="LEADERBOARD"back={()=>setMode("home")}/><section className="card leaders"><h1>TOP PLAYERS</h1>{leaders.length?leaders.map((p,i)=><div className="rank"key={i}><span>#{i+1} {p.name||"Player"}</span><b>{p.stats?.wins||0} W</b></div>):<p>NO SAVED PLAYERS YET</p>}</section></main>;
if(mode==="join")return <main><Top t="ONLINE MATCH"back={()=>setMode("home")}/><section className="card join"><div className="glitch">ENTER THE ARENA</div><input value={room}onChange={e=>setRoom(e.target.value)}placeholder="ROOM CODE"/><button onClick={()=>join()}>JOIN ROOM</button><div className="or">OR</div><button className="alt"onClick={create}>CREATE ROOM</button><p>{status}</p></section></main>;
return <Game title={mode==="bot"?"PRO BOT":"ONLINE // "+room}b={b}turn={turn}mark={mark}result={result}status={status}cell={mode==="bot"?bot:move}back={()=>setMode("home")}rematch={rematch}link={mode==="online"?link:""}copy={()=>{navigator.clipboard?.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1000)}}copied={copied}/>
}
function Top({t,back}){return <header><b>✦ XOX<span>NEON</span></b><strong>{t}</strong><button className="back"onClick={back}>ESC</button></header>}
function Home({name,setName,google,stats,bot,online,leaders,status}){return <main><header><b>✦ XOX<span>NEON</span></b><small>ARENA // ONLINE</small></header><section className="hero"><div className="eyebrow">TACTICAL GRID // 01</div><h1>X<span>O</span>X</h1><p>OUTPLAY. OUTTHINK. DOMINATE.</p><div className="buttons"><button onClick={bot}>⚡ PRO BOT</button><button onClick={online}>◈ ONLINE MATCH</button></div><button className="leaderBtn"onClick={leaders}>🏆 VIEW LEADERBOARD</button></section><section className="profile"><div><label>PLAYER ID</label><input value={name}onChange={e=>setName(e.target.value)}placeholder="Enter name to save stats"/></div><button className="google"onClick={google}>G&nbsp; SAVE WITH GOOGLE</button><div className="stats"><div><b>{stats.wins}</b><small>WINS</small></div><div><b>{stats.losses}</b><small>LOSSES</small></div><div><b>{stats.draws}</b><small>DRAWS</small></div></div>{status&&<small className="notice">{status}</small>}</section></main>}
function Game({title,b,turn,mark,result,status,cell,back,rematch,link,copy,copied}){return <main><Top t={title}back={back}/><section className="game"><div className="matchbar"><span>YOU <b className={mark==="X"?"x":"o"}>{mark}</b></span><strong>{status}</strong><span>TURN <b>{turn}</b></span></div><div className="board">{b.map((v,i)=><button key={i}disabled={!!v||!!result}onClick={()=>cell(i)}className={v?`cell ${v.toLowerCase()}`:""}>{v}</button>)}</div>{link&&<div className="invite"><small>INVITE FRIEND</small><div><input readOnly value={link}/><button onClick={copy}>{copied?"COPIED":"COPY"}</button></div></div>}{result&&<button className="wide"onClick={rematch}>↻ REMATCH</button>}</section></main>}
